force-app/main/default/objects/OLP_Run__c/OLP_Run__c.object-meta.xml
<CustomObject>
    <label>OLP Run</label>
    <nameField>
        <displayFormat>OLP-R-{0000000}</displayFormat>
        <label>OLP Run Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OLP Run</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OLP_Run__c/fields/Batch_Job_Id__c.field-meta.xml
<CustomField>
    <fullName>Batch_Job_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Batch Job Id</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/OLP_Run__c/fields/Count_of_Workers__c.field-meta.xml
<CustomField>
    <fullName>Count_of_Workers__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Count of Workers</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OLP_Run__c/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <label>End Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/OLP_Run__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Initialized</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Finished</fullName>
            </value>
            <value>
                <fullName>Finished (with errors)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OLP_Run__c/fields/Workers_Processed__c.field-meta.xml
<CustomField>
    <fullName>Workers_Processed__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Workers Processed</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OLP_Worker__c/OLP_Worker__c.object-meta.xml
<CustomObject>
    <label>OLP Worker</label>
    <nameField>
        <displayFormat>OLP-W-{0000000}</displayFormat>
        <label>OLP Worker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OLP Worker</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OLP_Worker__c/fields/OLP_Run__c.field-meta.xml
<CustomField>
    <fullName>OLP_Run__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>OLP Run</label>
    <referenceTo>OLP_Run__c</referenceTo>
    <relationshipLabel>OLP Worker</relationshipLabel>
    <relationshipName>OLP_Worker</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OLP_Worker__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OfflineProcessingBatchable.cls
public with sharing class OfflineProcessingBatchable implements Database.Batchable<SObject>, Database.AllowsCallouts, Database.Stateful
{
    private List<OLP_Worker__c> olpWorkers;
    private OLP_Run__c olpRun;
    private String queryStr;
    private String interval;
    private DateTime currTime;
    private Integer workersProcessed = 0;

    public OfflineProcessingBatchable(String queryStr, String interval, OLP_Run__c olpRun)
    {
        this.queryStr = queryStr;
        this.interval = interval;
        this.olpRun = olpRun;
        currTime = System.NOW();
    }

    public Database.QueryLocator start(Database.BatchableContext bc)
    {
        olpRun.Start_Time__c = System.NOW();
        olpRun.Batch_Job_Id__c = bc.getJobId();
        olpRun.Status__c = 'In Progress';
        update olpRun;
        return Database.getQueryLocator(queryStr);
    }

    public void execute(Database.BatchableContext bc, List<OLP_Worker__c> olpWorkers)
    {
        for(OLP_Worker__c worker: olpWorkers)
        {
            worker.OLP_Run__c = olpRun.Id;
            OfflineProcessing olpWork = new OfflineProcessing(worker);
            olpWork.doWork();
            workersProcessed++;
        }
        olpRun.Workers_Processed__c = workersProcessed;
        update olpRun;
        update olpWorkers;
    }

    public void finish(Database.BatchableContext bc)
    {
        olpRun.End_Time__c = System.NOW();
        olpRun.Status__c = 'Finished';
        if(olpRun.Count_of_Workers__c > 0) { 
            update olpRun;
        } else {
            delete olpRun;
        }
    }
}