force-app/main/default/objects/OLP_Worker__c/OLP_Worker__c.object-meta.xml
<CustomObject>
    <label>OLP Worker</label>
    <nameField>
        <displayFormat>OLP-W-{0000000}</displayFormat>
        <label>OLP Worker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OLP Worker</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OLP_Worker__c/fields/DML_Operation__c.field-meta.xml
<CustomField>
    <fullName>DML_Operation__c</fullName>
    <label>DML Operation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>INS</fullName>
            </value>
            <value>
                <fullName>UPDT</fullName>
            </value>
            <value>
                <fullName>UPST</fullName>
            </value>
            <value>
                <fullName>DLT</fullName>
            </value>
            <value>
                <fullName>UNDLT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OLP_Worker__c/fields/JSON_Parameters__c.field-meta.xml
<CustomField>
    <fullName>JSON_Parameters__c</fullName>
    <label>JSON Parameters</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/OLP_Worker__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OLP_Worker__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Flow</fullName>
            </value>
            <value>
                <fullName>SObject</fullName>
            </value>
            <value>
                <fullName>Apex Executable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OfflineProcessingSObjectInvocable.cls
public with sharing class OfflineProcessingSObjectInvocable
{
    public class Input
    {
        @InvocableVariable(label = 'SObjects')
        public List<SObject> sObjs;
        @InvocableVariable(label = 'DML Operation')
        public String operationType;
        @InvocableVariable(label = 'Configured Worker')
        public OLP_Worker__c worker;
    }

    public class Output
    {
        @InvocableVariable(label = 'Updated Worker')
        public OLP_Worker__c worker;

        public Output(OLP_Worker__c worker){
            this.worker = worker;
        }
    }

    @InvocableMethod(label = 'Process SObjects' category = 'Offline Processing')
    public static List<Output> submit(List<Input> inputs)
    {
        List<OLP_Worker__c> workersToQueue = new List<OLP_Worker__c>();
        List<Output> outputs = new List<Output>();
        for(Input inp: inputs)
        {
            OLP_Worker__c worker = new OLP_Worker__c();
            if(inp.worker != null) {
                worker = inp.worker;
            } else {
                worker.Type__c = 'SObject';
                worker.DML_Operation__c = inp.operationType;
            }
            worker.JSON_Parameters__c = JSON.serialize(inp.sObjs);
            worker.Status__c = 'Pending';
            workersToQueue.add(worker);
            Output output = new Output(worker);
            outputs.add(output);
        }
        insert as system workersToQueue;
        return outputs;
    }
}