force-app/main/default/objects/Row_2_Flow_Configuration__mdt/Row_2_Flow_Configuration__mdt.object-meta.xml
<CustomObject>
    <label>Row 2 Flow Configuration</label>
    <pluralLabel>Row 2 Flow Configuration</pluralLabel>
</CustomObject>

force-app/main/default/objects/Row_2_Flow_Configuration__mdt/fields/Batch_Size__c.field-meta.xml
<CustomField>
    <fullName>Batch_Size__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Batch Size</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Row_2_Flow_Configuration__mdt/fields/Flow_API__c.field-meta.xml
<CustomField>
    <fullName>Flow_API__c</fullName>
    <description>UBS-3224 - Added</description>
    <label>Flow API</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Row_2_Flow_Configuration__mdt/fields/Generate_Per_Run_Results_File__c.field-meta.xml
<CustomField>
    <fullName>Generate_Per_Run_Results_File__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Generate Per Run Results File</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Row_2_Flow_Configuration__mdt/fields/Generate_Results_Record__c.field-meta.xml
<CustomField>
    <fullName>Generate_Results_Record__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Generate Results Record</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Row_2_Flow_Configuration__mdt/fields/List_View_Id_API_Name__c.field-meta.xml
<CustomField>
    <fullName>List_View_Id_API_Name__c</fullName>
    <label>List View Id or API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Row_2_Flow_Configuration__mdt/fields/Report_Id_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Report_Id_API_Name__c</fullName>
    <label>Report Id or API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Row_2_Flow_Configuration__mdt/fields/SOQL_Query_Filter_Conditions__c.field-meta.xml
<CustomField>
    <fullName>SOQL_Query_Filter_Conditions__c</fullName>
    <description>UBS-3667 - Added for Row2Flow SOQL support</description>
    <label>SOQL Query Filter Conditions</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Row_2_Flow_Configuration__mdt/fields/Source_Type__c.field-meta.xml
<CustomField>
    <fullName>Source_Type__c</fullName>
    <label>Source Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Report</fullName>
                <default>true</default>
                <label>Report</label>
            </value>
            <value>
                <fullName>List View</fullName>
            </value>
            <value>
                <fullName>SOQL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Row_2_Flow_Configuration__mdt/fields/Unique_Column_Header__c.field-meta.xml
<CustomField>
    <fullName>Unique_Column_Header__c</fullName>
    <description>UBS-3667 - Remove uniqueness and require via validation rule if type is Report</description>
    <label>Unique Column Header</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Row_2_Flow_Mapping__mdt/Row_2_Flow_Mapping__mdt.object-meta.xml
<CustomObject>
    <label>Row 2 Flow Mapping</label>
    <pluralLabel>Row 2 Flow Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Row_2_Flow_Mapping__mdt/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>UBS-3224 - Added</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Row_2_Flow_Mapping__mdt/fields/Data_Type__c.field-meta.xml
<CustomField>
    <fullName>Data_Type__c</fullName>
    <description>UBS-3224 - Added</description>
    <label>Data Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Boolean</fullName>
                <default>true</default>
                <label>Boolean</label>
            </value>
            <value>
                <fullName>Integer</fullName>
            </value>
            <value>
                <fullName>Decimal</fullName>
            </value>
            <value>
                <fullName>Date</fullName>
            </value>
            <value>
                <fullName>Date/Time</fullName>
            </value>
            <value>
                <fullName>String</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Row_2_Flow_Mapping__mdt/fields/Row_2_Flow_Configuration__c.field-meta.xml
<CustomField>
    <fullName>Row_2_Flow_Configuration__c</fullName>
    <label>Row 2 Flow Configuration</label>
    <referenceTo>Row_2_Flow_Configuration__mdt</referenceTo>
    <relationshipLabel>Row 2 Flow Mappings</relationshipLabel>
    <relationshipName>Row_2_Flow_Mappings</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Row_2_Flow_Mapping__mdt/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <description>UBS-3224 - Added</description>
    <inlineHelpText>For static, this field will be the flow input variable API (case sensitive); for report value, this field will represent the report column header API (use report describe to ensure exact match)</inlineHelpText>
    <label>Source</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Row_2_Flow_Mapping__mdt/fields/Target__c.field-meta.xml
<CustomField>
    <fullName>Target__c</fullName>
    <description>UBS-3224 - Added</description>
    <inlineHelpText>For static, this field will represent the actual value; for report value this field will be the flow input variable API (case sensitive)</inlineHelpText>
    <label>Target</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Row_2_Flow_Mapping__mdt/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>UBS-3667 - Change &quot;Report Value&quot; to &quot;Source Value&quot;</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Source Value</fullName>
                <default>true</default>
                <label>Source Value</label>
            </value>
            <value>
                <fullName>Static</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Row_2_Flow_Run_Result__c/Row_2_Flow_Run_Result__c.object-meta.xml
<CustomObject>
    <label>Row 2 Flow Run Result</label>
    <nameField>
        <displayFormat>R2F-R-{000000}</displayFormat>
        <label>Row 2 Flow Run Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Row 2 Flow Run Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Row_2_Flow_Run_Result__c/fields/Configuration_Name__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Name__c</fullName>
    <label>Configuration Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Row_2_Flow_Run_Result__c/fields/Flow__c.field-meta.xml
<CustomField>
    <fullName>Flow__c</fullName>
    <label>Flow</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Row_2_Flow_Run_Result__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Report</fullName>
            </value>
            <value>
                <fullName>SOQL</fullName>
            </value>
            <value>
                <fullName>List View</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Row2FlowBase.cls
/**
 * Author: Kyle Bentsen
 * GitHub: https://github.com/k-bentsen/Row2Flow
 * License: BSD 3-Clause License
 */

public virtual class Row2FlowBase
{
    protected String flowName;
    protected Map<String, String> fieldToFlowInput = new Map<String, String>();
    protected Map<String, Object> staticFlowParamValues = new Map<String, Object>();

    protected Schema.SObjectType sObjType;

    protected Boolean generateResultsRec = false;
    protected Row2FlowResultsHandler resultsHandler;

    protected String jobName = 'Anonymous Row 2 Flow Job';

    public Row2FlowBase() 
    {
        this.flowName = null;
    }
    
    public Row2FlowBase(String flowName, Map<String, String> fieldToFlowInput)
    {
        this.flowName = flowName;
        this.fieldToFlowInput = fieldToFlowInput;
        this.resultsHandler = new Row2FlowResultsHandler(new Row_2_Flow_Run_Result__c(Flow__c = this.flowName));
    }

    public Row2FlowBase(Row_2_Flow_Configuration__mdt config) 
    {
        this.flowName = config.Flow_API__c;
        List<Row_2_Flow_Mapping__mdt> configInputs = [SELECT Source__c, Target__c, Type__c, Data_Type__c FROM Row_2_Flow_Mapping__mdt WHERE Row_2_Flow_Configuration__c = :config.Id AND Active__c = TRUE];
        for(Row_2_Flow_Mapping__mdt mapping: configInputs)
        {
            if(mapping.Type__c == 'Static')
            {
                Object val = convertDataType(mapping);
                staticFlowParamValues.put(mapping.Target__c, val);
            } else if(mapping.Type__c == 'Source Value'){
                fieldToFlowInput.put(mapping.Source__c, mapping.Target__c);
            }
        }

        this.resultsHandler = new Row2FlowResultsHandler(new Row_2_Flow_Run_Result__c(Flow__c = this.flowName, Configuration_Name__c = config.DeveloperName, Type__c = config.Source_Type__c));
        if(config.Generate_Results_Record__c) {
            saveResultFile(config.Generate_Per_Run_Results_File__c);
        }
    }

    public void addStaticFlowParams(Map<String, Object> staticFlowParamValues)
    {
        this.staticFlowParamValues.putAll(staticFlowParamValues);
    }

    public void saveResultFile(Boolean generatePerRunFile)
    {
        this.generateResultsRec = true;
        if(generatePerRunFile) {
            this.resultsHandler.setGeneratePerRunResultFile();
        }
    }

    protected virtual FlowResult runFlow(Flow.Interview flowToRun)
    {
        return defaultFlowRun(flowToRun);
    }

    @testVisible
    private FlowResult defaultFlowRun(Flow.Interview flowToRun)
    {
        FlowResult fr = new FlowResult();
        try {
            flowToRun.start();
            if(Test.isRunningTest() && throwTestException) {
                throw new FlowException('An error has occurred in flow ' + flowName);
            }
            fr.success = true;
        } catch (Exception e) {
            fr.failureMsg = e.getMessage();
        }
        return fr;
    }

    protected void processFlow(Map<String, Object> flowParams)
    {
        Flow.Interview flowInstance = Flow.Interview.createInterview(flowName, flowParams);
        Row2FlowBase.FlowResult fr = runFlow(flowInstance);
        resultsHandler.handleFlowResults(fr);
    }

    @testVisible
    protected Object convertDataType(Row_2_Flow_Mapping__mdt mapping)
    {
        Object val = null;
        switch on mapping.Data_Type__c
        {
            when 'Boolean' {
                val = Boolean.valueOf(mapping.Source__c);
            }
            when 'Integer' {
                val = Integer.valueOf(mapping.Source__c);
            }
            when 'Decimal' {
                val = Decimal.valueOf(mapping.Source__c);
            }
            when 'Date' {
                val = Date.valueOf(mapping.Source__c);
            }
            when 'Date/Time' {
                val = Datetime.valueOf(mapping.Source__c);
            }
            when 'String' {
                val = String.valueOf(mapping.Source__c);
            }
        }
        return val;
    }

    protected void setStartTime()
    {
        this.resultsHandler.getRecord().Start_Time__c = System.NOW();
    }

    public static Row_2_Flow_Configuration__mdt configQuery(String configName)
    {
        return [SELECT DeveloperName, MasterLabel, Active__c, Batch_Size__c, Source_Type__c, Flow_API__c, Report_Id_API_Name__c, Unique_Column_Header__c, SOQL_Query_Filter_Conditions__c, List_View_Id_API_Name__c, Generate_Results_Record__c, Generate_Per_Run_Results_File__c FROM Row_2_Flow_Configuration__mdt WHERE DeveloperName = :configName];
    }

    public class FlowResult
    {
        @InvocableVariable
        public Boolean success = false;
        @InvocableVariable
        public Row_2_Flow_Configuration__mdt config;
        @InvocableVariable
        public String failureMsg;
        @InvocableVariable
        public String jobId;
    }

    @testVisible
    private static Boolean throwTestException = false;
}