force-app/main/default/objects/Row_2_Flow_Configuration__mdt/Row_2_Flow_Configuration__mdt.object-meta.xml
<CustomObject>
    <label>Row 2 Flow Configuration</label>
    <pluralLabel>Row 2 Flow Configuration</pluralLabel>
</CustomObject>

force-app/main/default/objects/Row_2_Flow_Configuration__mdt/fields/Flow_API__c.field-meta.xml
<CustomField>
    <fullName>Flow_API__c</fullName>
    <description>UBS-3224 - Added</description>
    <label>Flow API</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Row_2_Flow_Mapping__mdt/Row_2_Flow_Mapping__mdt.object-meta.xml
<CustomObject>
    <label>Row 2 Flow Mapping</label>
    <pluralLabel>Row 2 Flow Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Row_2_Flow_Mapping__mdt/fields/Data_Type__c.field-meta.xml
<CustomField>
    <fullName>Data_Type__c</fullName>
    <description>UBS-3224 - Added</description>
    <label>Data Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Boolean</fullName>
                <default>true</default>
                <label>Boolean</label>
            </value>
            <value>
                <fullName>Integer</fullName>
            </value>
            <value>
                <fullName>Decimal</fullName>
            </value>
            <value>
                <fullName>Date</fullName>
            </value>
            <value>
                <fullName>Date/Time</fullName>
            </value>
            <value>
                <fullName>String</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Row_2_Flow_Mapping__mdt/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <description>UBS-3224 - Added</description>
    <inlineHelpText>For static, this field will be the flow input variable API (case sensitive); for report value, this field will represent the report column header API (use report describe to ensure exact match)</inlineHelpText>
    <label>Source</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Row_2_Flow_Run_Result__c/Row_2_Flow_Run_Result__c.object-meta.xml
<CustomObject>
    <label>Row 2 Flow Run Result</label>
    <nameField>
        <displayFormat>R2F-R-{000000}</displayFormat>
        <label>Row 2 Flow Run Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Row 2 Flow Run Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Row_2_Flow_Run_Result__c/fields/Number_Failure_Rows__c.field-meta.xml
<CustomField>
    <fullName>Number_Failure_Rows__c</fullName>
    <label>Number Failure Rows</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/Row2FlowBaseTest.cls
/**
 * Author: Kyle Bentsen
 * GitHub: https://github.com/k-bentsen/Row2Flow
 * License: BSD 3-Clause License
 */

@IsTest
private class Row2FlowBaseTest
{
    @isTest
    private static void forceError()
    {
        Row2FlowTestUtils.insertTestRecords(5);
        Row2FlowBase.throwTestException = true;
        Row_2_Flow_Configuration__mdt soqlConfig = Row_2_Flow_Configuration__mdt.getAll().get('SOQL_Test');
        Row2FlowSOQLBatchable soqlBatchRun = new Row2FlowSOQLBatchable(soqlConfig);
        soqlBatchRun.saveResultFile(true);
        Id batchJobId;

        Test.startTest();
            batchJobId = Database.executeBatch(soqlBatchRun);
        Test.stopTest();

        Row_2_Flow_Run_Result__c runResult = Row2FlowTestUtils.getResult(batchJobId);
        Assert.areEqual(5, runResult.Number_Failure_Rows__c);
        ContentDocumentLink resultCDL = [SELECT ContentDocumentId FROM ContentDocumentLink WHERE LinkedEntityId =: runResult.Id];
        List<ContentVersion> result = [SELECT VersionData FROM ContentVersion WHERE ContentDocumentId =: resultCDL.ContentDocumentId];
        String fileBody = result[0].VersionData.toString();
        Assert.isTrue(fileBody.contains('Failure Records(5)'));
        Assert.isTrue(fileBody.contains(Row2FlowTestUtils.accts[0].Id + ' => An error has occurred in flow ' + soqlConfig.Flow_API__c));
    }

    @isTest
    private static void dataConversions()
    {
        Map<String, String> data = new Map<String, String>{'Boolean' => 'false', 'Integer' => '5', 'Decimal' => '10.0', 'Date' => '2022-01-01', 'Date/Time' => '2022-01-01 00:00:00', 'String' => 'string'};
        Row2FlowBase baseInstance = new Row2FlowBase();
        Boolean convertErr = false;
        
        Test.startTest();
            for(String dataType: data.keySet()) {
                Row_2_Flow_Mapping__mdt mapping = new Row_2_Flow_Mapping__mdt();
                mapping.Data_Type__c = dataType;
                mapping.Source__c = data.get(dataType);
                try {
                    baseInstance.convertDataType(mapping);
                } catch(Exception e){
                    convertErr = true;
                }
            }
        Test.stopTest();

        Assert.isFalse(convertErr);
    }
}