force-app/main/default/objects/Row_2_Flow_Configuration__mdt/Row_2_Flow_Configuration__mdt.object-meta.xml
<CustomObject>
    <label>Row 2 Flow Configuration</label>
    <pluralLabel>Row 2 Flow Configuration</pluralLabel>
</CustomObject>

force-app/main/default/objects/Row_2_Flow_Configuration__mdt/fields/Report_Id_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Report_Id_API_Name__c</fullName>
    <label>Report Id or API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Row_2_Flow_Run_Result__c/Row_2_Flow_Run_Result__c.object-meta.xml
<CustomObject>
    <label>Row 2 Flow Run Result</label>
    <nameField>
        <displayFormat>R2F-R-{000000}</displayFormat>
        <label>Row 2 Flow Run Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Row 2 Flow Run Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Row_2_Flow_Run_Result__c/fields/Configuration_Name__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Name__c</fullName>
    <label>Configuration Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Row_2_Flow_Run_Result__c/fields/Flow__c.field-meta.xml
<CustomField>
    <fullName>Flow__c</fullName>
    <label>Flow</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Row_2_Flow_Run_Result__c/fields/Number_Success_Rows__c.field-meta.xml
<CustomField>
    <fullName>Number_Success_Rows__c</fullName>
    <label>Number Success Rows</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Row_2_Flow_Run_Result__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Report</fullName>
            </value>
            <value>
                <fullName>SOQL</fullName>
            </value>
            <value>
                <fullName>List View</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Row2FlowReportTest.cls
/**
 * Author: Kyle Bentsen
 * GitHub: https://github.com/k-bentsen/Row2Flow
 * License: BSD 3-Clause License
 */

@IsTest (SeeAllData=true)
private class Row2FlowReportTest
{
    private static final Report testReport = [SELECT Id FROM Report WHERE DeveloperName = 'Row_2_Flow_Test_Report'];
    private static Id batchJobId;
    private static Row_2_Flow_Configuration__mdt reportConfig = Row_2_Flow_Configuration__mdt.getAll().get('Report_Test');
    private static Row2FlowReportBatchable reportBatchRun;
    private static Row_2_Flow_Run_Result__c runResult;

    @isTest
    private static void runReportBase()
    {
        Row2FlowTestUtils.insertTestRecords(1);
        reportBatchRun = new Row2FlowReportBatchable('Row_2_Flow_Test_Report', 'ACCOUNT.NAME', 'Row_2_Flow_Test_Headless_Flow', new Map<String, String> {'StaticTextInput' => 'Default'})
            .withStaticFlowParams(new Map<String, Object>{'Pass' => true});
        reportBatchRun.saveResultFile(false);
        
        Test.startTest();
            batchJobId = Database.executeBatch(reportBatchRun);
        Test.stopTest();

        runResult = Row2FlowTestUtils.getResult(batchJobId);
        Assert.areEqual('Row_2_Flow_Test_Headless_Flow', runResult.Flow__c);
        Assert.areEqual('Report', runResult.Type__c);
        Assert.areEqual(1, runResult.Number_Success_Rows__c);
    }

    @isTest
    private static void runReportFromConfig()
    {
        Row2FlowTestUtils.insertTestRecords(1);
        reportConfig = Row2FlowBase.configQuery('Report_Test');
        reportConfig.Report_Id_API_Name__c = testReport.Id;
        reportBatchRun = new Row2FlowReportBatchable(reportConfig);

        Test.startTest();
            batchJobId = Database.executeBatch(reportBatchRun);
        Test.stopTest();

        runResult = Row2FlowTestUtils.getResult(batchJobId);
        Assert.areEqual('Report_Test', runResult.Configuration_Name__c);
        Assert.areEqual('Report', runResult.Type__c);
    }

    @isTest 
    private static void printColumnHeaders()
    {
        Test.startTest();
            String output = Row2FlowReportUtils.printReportColumnsbyId(testReport.Id);
        Test.stopTest();

        Assert.isTrue(output.contains('ACCOUNT.NAME'));
    }

    @isTest 
    private static void printColumnHeadersByAPIName()
    {
        Test.startTest();
            String output = Row2FlowReportUtils.printReportColumns('Row_2_Flow_Test_Report');
        Test.stopTest();

        Assert.isTrue(output.contains('ACCOUNT.NAME'));
    }
}