force-app/main/default/objects/Row_2_Flow_Configuration__mdt/Row_2_Flow_Configuration__mdt.object-meta.xml
<CustomObject>
    <label>Row 2 Flow Configuration</label>
    <pluralLabel>Row 2 Flow Configuration</pluralLabel>
</CustomObject>

force-app/main/default/objects/Row_2_Flow_Run_Result__c/Row_2_Flow_Run_Result__c.object-meta.xml
<CustomObject>
    <label>Row 2 Flow Run Result</label>
    <nameField>
        <displayFormat>R2F-R-{000000}</displayFormat>
        <label>Row 2 Flow Run Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Row 2 Flow Run Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Row_2_Flow_Run_Result__c/fields/Flow__c.field-meta.xml
<CustomField>
    <fullName>Flow__c</fullName>
    <label>Flow</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Row_2_Flow_Run_Result__c/fields/Number_Success_Rows__c.field-meta.xml
<CustomField>
    <fullName>Number_Success_Rows__c</fullName>
    <label>Number Success Rows</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Row_2_Flow_Run_Result__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Report</fullName>
            </value>
            <value>
                <fullName>SOQL</fullName>
            </value>
            <value>
                <fullName>List View</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Row2FlowListViewTest.cls
/**
 * Author: Kyle Bentsen
 * GitHub: https://github.com/k-bentsen/Row2Flow
 * License: BSD 3-Clause License
 */

@isTest
private class Row2FlowListViewTest
{
    private static Row_2_Flow_Configuration__mdt listViewConfig = Row_2_Flow_Configuration__mdt.getAll().get('List_View_Test');
    private static Id batchJobId;
    private static Row2FlowListViewBatchable listViewBatchRun;
    

    @isTest
    private static void listViewRun()
    {
        Row2FlowTestUtils.insertTestRecords(1);
        listViewBatchRun = new Row2FlowListViewBatchable(listViewConfig);

        Test.startTest();
            Test.setMock(HttpCalloutMock.class, new Row2FlowTestUtils.ListViewDescribeMock());
            batchJobId =Database.executeBatch(listViewBatchRun);
        Test.stopTest();

        Row_2_Flow_Run_Result__c runResult = Row2FlowTestUtils.getResult(batchJobId);
        Assert.areEqual('Row_2_Flow_Test_Headless_Flow', runResult.Flow__c);
        Assert.areEqual('List View', runResult.Type__c);
        Assert.areEqual(1, runResult.Number_Success_Rows__c);
    }
}